# Site settings
title: Your Site Title
email: your-email@example.com
description: >-
  Write a description for your site here.
baseurl: ""
url: "https://your-site-url.com"

# Social Media Links
twitter_username: your_twitter_username
github_username: your_github_username

# Build settings
markdown: kramdown
