# Site settings
title: GRANDOASIS
email: qq80869098@gmail.com
description: >-
  Write a description for your site here.
baseurl: "https://github.com/BaiyingQiu/GRANDOASIS"
url: "BaiyingQiu.github.io"

# Social Media Links
twitter_username: your_twitter_username
github_username: your_github_username

# Build settings
markdown: kramdown
